server.port=8080

# 로그 레벨
logging.level.com.samteo=INFO
logging.level.org.springframework.web=WARN

# 관광인 API (empmnInfoList)
external.gwanwangin.base-url=https://apis.data.go.kr/B551011/tursmService
external.gwanwangin.api-key=${API_SERVICE_KEY:}

# TourAPI
external.tourapi.base-url=https://apis.data.go.kr/B551011/KorService2
external.tourapi.service-key=${API_SERVICE_KEY:}
