server.port=8080

# 로그 레벨
logging.level.com.samteo=INFO
logging.level.org.springframework.web=WARN

# 관광인 API (empmnInfoList)
external.gwanwangin.base-url=https://apis.data.go.kr/B551011/tursmService
external.gwanwangin.api-key=jrpDc6Lvhm1DiaQ7DImECa4IVsTxoEGAbPIc5d0xe6xOh0yDhYosrgABLBZG8d8gxlK%2BAZ%2FtkDTGoZ5CP%2FfE9w%3D%3D

# TourAPI
external.tourapi.base-url=https://apis.data.go.kr/B551011/KorService2
external.tourapi.service-key=jrpDc6Lvhm1DiaQ7DImECa4IVsTxoEGAbPIc5d0xe6xOh0yDhYosrgABLBZG8d8gxlK%2BAZ%2FtkDTGoZ5CP%2FfE9w%3D%3D
