spring.application.name=samteo
spring.profiles.active=dev
spring.config.import=optional:classpath:application-secret.properties

# Shared properties
kakao.redirect.uri=http://localhost:8080/login/oauth2/code/kakao
