CREATE DATABASE IF NOT EXISTS `samteo_db`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `samteo_db`;

DROP TABLE IF EXISTS `TOUR_API_SYNC_HISTORY`;
DROP TABLE IF EXISTS `TOUR_CONTENT_REPEAT_INFO`;
DROP TABLE IF EXISTS `DETAIL_RESTAURANT`;
DROP TABLE IF EXISTS `DETAIL_SHOPPING`;
DROP TABLE IF EXISTS `DETAIL_ACCOMMODATION`;
DROP TABLE IF EXISTS `DETAIL_COURSE`;
DROP TABLE IF EXISTS `DETAIL_FESTIVAL`;
DROP TABLE IF EXISTS `DETAIL_CULTURE_FACILITY`;
DROP TABLE IF EXISTS `DETAIL_TOURSPOT`;
DROP TABLE IF EXISTS `TOUR_CONTENT_OVERVIEW`;
DROP TABLE IF EXISTS `TOUR_CONTENT_IMAGE`;
DROP TABLE IF EXISTS `TOUR_CONTENT`;
DROP TABLE IF EXISTS `META_SIGUNGU`;
DROP TABLE IF EXISTS `META_CONTENT_TYPE`;
DROP TABLE IF EXISTS `META_AREA`;

DROP TABLE IF EXISTS `accommodation_tags`;
DROP TABLE IF EXISTS `job_tags`;
DROP TABLE IF EXISTS `region_recommendation_reasons`;
DROP TABLE IF EXISTS `region_tags`;
DROP TABLE IF EXISTS `accommodations`;
DROP TABLE IF EXISTS `jobs`;
DROP TABLE IF EXISTS `regions`;

DROP TABLE IF EXISTS `PLAN_CALENDAR`;
DROP TABLE IF EXISTS `PLAN_JOB`;
DROP TABLE IF EXISTS `PLAN`;
DROP TABLE IF EXISTS `ACC_DISPOSABLE`;
DROP TABLE IF EXISTS `ACC_TAG`;
DROP TABLE IF EXISTS `ACCOMMODATION`;
DROP TABLE IF EXISTS `JOB_TAG`;
DROP TABLE IF EXISTS `JOB`;
DROP TABLE IF EXISTS `FESTIVAL`;
DROP TABLE IF EXISTS `JOB_TYPE`;
DROP TABLE IF EXISTS `REGION`;
