CREATE DATABASE IF NOT EXISTS `samteo_db`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `samteo_db`;

DROP TABLE IF EXISTS `planner_schedules`;
DROP TABLE IF EXISTS `planner_event_types`;
DROP TABLE IF EXISTS `personal_planners`;

DROP TABLE IF EXISTS `TOUR_API_SYNC_HISTORY`;
DROP TABLE IF EXISTS `TOUR_CONTENT_REPEAT_INFO`;
DROP TABLE IF EXISTS `DETAIL_RESTAURANT`;
DROP TABLE IF EXISTS `DETAIL_SHOPPING`;
DROP TABLE IF EXISTS `DETAIL_ACCOMMODATION`;
DROP TABLE IF EXISTS `DETAIL_COURSE`;
DROP TABLE IF EXISTS `DETAIL_FESTIVAL`;
DROP TABLE IF EXISTS `DETAIL_CULTURE_FACILITY`;
DROP TABLE IF EXISTS `DETAIL_TOURSPOT`;
DROP TABLE IF EXISTS `TOUR_CONTENT_OVERVIEW`;
DROP TABLE IF EXISTS `TOUR_CONTENT_IMAGE`;
DROP TABLE IF EXISTS `TOUR_CONTENT`;
DROP TABLE IF EXISTS `META_SIGUNGU`;
DROP TABLE IF EXISTS `META_CONTENT_TYPE`;
DROP TABLE IF EXISTS `META_AREA`;
DROP TABLE IF EXISTS `USER`;

DROP TABLE IF EXISTS `tour_api_sync_history`;
DROP TABLE IF EXISTS `tour_content_repeat_info`;
DROP TABLE IF EXISTS `detail_restaurant`;
DROP TABLE IF EXISTS `detail_shopping`;
DROP TABLE IF EXISTS `detail_accommodation`;
DROP TABLE IF EXISTS `detail_course`;
DROP TABLE IF EXISTS `detail_festival`;
DROP TABLE IF EXISTS `detail_culture_facility`;
DROP TABLE IF EXISTS `detail_tourspot`;
DROP TABLE IF EXISTS `tour_content_overview`;
DROP TABLE IF EXISTS `tour_content_image`;
DROP TABLE IF EXISTS `tour_content`;
DROP TABLE IF EXISTS `meta_sigungu`;
DROP TABLE IF EXISTS `meta_content_type`;
DROP TABLE IF EXISTS `meta_area`;

DROP TABLE IF EXISTS `accommodation_tags`;
DROP TABLE IF EXISTS `job_tags`;
DROP TABLE IF EXISTS `region_recommendation_reasons`;
DROP TABLE IF EXISTS `region_tags`;
DROP TABLE IF EXISTS `accommodations`;
DROP TABLE IF EXISTS `jobs`;
DROP TABLE IF EXISTS `regions`;

DROP TABLE IF EXISTS `plan_calendar`;
DROP TABLE IF EXISTS `plan_job`;
DROP TABLE IF EXISTS `plan`;
DROP TABLE IF EXISTS `acc_disposable`;
DROP TABLE IF EXISTS `acc_tag`;
DROP TABLE IF EXISTS `accommodation`;
DROP TABLE IF EXISTS `job_tag`;
DROP TABLE IF EXISTS `job`;
DROP TABLE IF EXISTS `festival`;
DROP TABLE IF EXISTS `job_type`;
DROP TABLE IF EXISTS `region`;

DROP TABLE IF EXISTS `users`;
